# Data Storytelling for NBA Boxscore Dataset

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
games = pd.read_csv('C:/Users/michael.thabane/Documents/Springboard/Capstone2/nba-games/games.csv')
games_details = pd.read_csv('C:/Users/michael.thabane/Documents/Springboard/Capstone2/nba-games/games_details.csv')
players = pd.read_csv('C:/Users/michael.thabane/Documents/Springboard/Capstone2/nba-games/players.csv')
standings = pd.read_csv('C:/Users/michael.thabane/Documents/Springboard/Capstone2/nba-games/ranking.csv')

### Data Wrangling Steps Taken in First Notebook

In [2]:
# convert date string to datetime variable
from datetime import datetime
games['GAME_DATE_EST'] = [datetime.strptime(x,'%Y-%m-%d') for x in games['GAME_DATE_EST']]
standings['STANDINGSDATE'] = [datetime.strptime(x,'%Y-%m-%d') for x in standings['STANDINGSDATE']]

In [3]:
final_boxscore = games_details.merge(games, left_on='GAME_ID', right_on="GAME_ID", how='inner')

In [4]:
final_boxscore = final_boxscore[['SEASON','GAME_ID','GAME_DATE_EST','TEAM_ID','HOME_TEAM_ID','VISITOR_TEAM_ID','TEAM_ABBREVIATION',
                                'TEAM_CITY','PLAYER_ID','PLAYER_NAME','START_POSITION','MIN', 'PTS','FGM','FGA','FG_PCT',
                                'FG3M', 'FG3A','FG3_PCT','FTM','FTA','FT_PCT','OREB', 'DREB', 'REB', 'AST', 'STL', 'BLK', 'TO',
                                'PF', 'PLUS_MINUS','PTS_home','PTS_away', 'AST_home','AST_away','REB_home','REB_away',
                                'FG_PCT_home','FG_PCT_away','FT_PCT_home','FT_PCT_away','FG3_PCT_home','FG3_PCT_away']]

In [5]:
final_boxscore['GAME_LOC'] = np.where(final_boxscore['TEAM_ID'] == final_boxscore['HOME_TEAM_ID'], 'HOME','AWAY')

In [6]:
final_boxscore['TOT_PTS'] = np.where(final_boxscore['GAME_LOC'] == 'HOME', final_boxscore['PTS_home'] , final_boxscore['PTS_away'])
final_boxscore['TOT_AST'] = np.where(final_boxscore['GAME_LOC'] == 'HOME', final_boxscore['AST_home'] , final_boxscore['AST_away'])
final_boxscore['TOT_REB'] = np.where(final_boxscore['GAME_LOC'] == 'HOME', final_boxscore['REB_home'] , final_boxscore['REB_away'])
final_boxscore['TOT_FG_PCT'] = np.where(final_boxscore['GAME_LOC'] == 'HOME', final_boxscore['FG_PCT_home'] , final_boxscore['FG_PCT_away'])
final_boxscore['TOT_FT_PCT'] = np.where(final_boxscore['GAME_LOC'] == 'HOME', final_boxscore['FT_PCT_home'] , final_boxscore['FT_PCT_away'])
final_boxscore['TOT_FG3_PCT'] = np.where(final_boxscore['GAME_LOC'] == 'HOME', final_boxscore['FG3_PCT_home'] , final_boxscore['FG3_PCT_away'])

In [7]:
final_boxscore = final_boxscore[['SEASON','GAME_ID','GAME_DATE_EST','TEAM_ID','HOME_TEAM_ID','VISITOR_TEAM_ID','TEAM_ABBREVIATION',
                                'TEAM_CITY','GAME_LOC','PLAYER_ID','PLAYER_NAME','START_POSITION','MIN', 'PTS','FGM','FGA',
                                'FG_PCT','FG3M', 'FG3A','FG3_PCT','FTM','FTA','FT_PCT','OREB', 'DREB', 'REB', 'AST', 'STL', 
                                'BLK','TO', 'PF', 'PLUS_MINUS','TOT_PTS','TOT_AST','TOT_REB','TOT_FG_PCT','TOT_FT_PCT',
                                'TOT_FG3_PCT']]

In [8]:
final_boxscore.set_index('GAME_DATE_EST')

,SEASON,GAME_ID,TEAM_ID,HOME_TEAM_ID,VISITOR_TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,GAME_LOC,PLAYER_ID,PLAYER_NAME,...,BLK,TO,PF,PLUS_MINUS,TOT_PTS,TOT_AST,TOT_REB,TOT_FG_PCT,TOT_FT_PCT,TOT_FG3_PCT
GAME_DATE_EST,,,,,,,,,,,,,,,,,,,,,
2020-03-01,2019,21900895,1610612749,1610612766,1610612749,MIL,Milwaukee,AWAY,202083,Wesley Matthews,...,0.0,0.0,0.0,11.0,93.0,20.0,61.0,0.402,0.762,0.226
2020-03-01,2019,21900895,1610612749,1610612766,1610612749,MIL,Milwaukee,AWAY,203507,Giannis Antetokounmpo,...,0.0,3.0,2.0,22.0,93.0,20.0,61.0,0.402,0.762,0.226
2020-03-01,2019,21900895,1610612749,1610612766,1610612749,MIL,Milwaukee,AWAY,201572,Brook Lopez,...,3.0,0.0,2.0,16.0,93.0,20.0,61.0,0.402,0.762,0.226
2020-03-01,2019,21900895,1610612749,1610612766,1610612749,MIL,Milwaukee,AWAY,1628978,Donte DiVincenzo,...,1.0,2.0,0.0,14.0,93.0,20.0,61.0,0.402,0.762,0.226
2020-03-01,2019,21900895,1610612749,1610612766,1610612749,MIL,Milwaukee,AWAY,202339,Eric Bledsoe,...,0.0,3.0,2.0,6.0,93.0,20.0,61.0,0.402,0.762,0.226
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2012-10-06,2012,11200005,1610612743,1610612746,1610612743,DEN,Denver,AWAY,202706,Jordan Hamilton,...,0.0,1.0,3.0,NaN,106.0,25.0,34.0,0.532,0.615,0.471
2012-10-06,2012,11200005,1610612743,1610612746,1610612743,DEN,Denver,AWAY,202702,Kenneth Faried,...,0.0,3.0,3.0,NaN,106.0,25.0,34.0,0.532,0.615,0.471
2012-10-06,2012,11200005,1610612743,1610612746,1610612743,DEN,Denver,AWAY,201585,Kosta Koufos,...,0.0,0.0,3.0,NaN,106.0,25.0,34.0,0.532,0.615,0.471
2012-10-06,2012,11200005,1610612743,1610612746,1610612743,DEN,Denver,AWAY,202389,Timofey Mozgov,...,0.0,4.0,2.0,NaN,106.0,25.0,34.0,0.532,0.615,0.471
2012-10-06,2012,11200005,1610612743,1610612746,1610612743,DEN,Denver,AWAY,201951,Ty Lawson,...,0.0,6.0,1.0,NaN,106.0,25.0,34.0,0.532,0.615,0.471

#### Let us only get data from players who have started a game in the 2019/2020 season

In [9]:
Start_guard = final_boxscore.loc[final_boxscore['START_POSITION'] == 'G']
Start_forward = final_boxscore.loc[final_boxscore['START_POSITION'] == 'F']
Start_Center = final_boxscore.loc[final_boxscore['START_POSITION'] == 'C']
Starters = Start_guard.append(Start_forward.append(Start_Center))
Starters = Starters.reset_index(drop= True)

In [10]:
started2019 = Starters.loc[Starters['SEASON'] == 2019]
SPI = started2019['PLAYER_ID'].unique()
Started_2019 = pd.DataFrame(columns = final_boxscore.columns)

In [11]:
for playerID in SPI:
    Data_Append = final_boxscore[final_boxscore['PLAYER_ID'] == playerID]
    Started_2019 = Started_2019.append(Data_Append)

In [12]:
Started_2019

,SEASON,GAME_ID,GAME_DATE_EST,TEAM_ID,HOME_TEAM_ID,VISITOR_TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,GAME_LOC,PLAYER_ID,...,BLK,TO,PF,PLUS_MINUS,TOT_PTS,TOT_AST,TOT_REB,TOT_FG_PCT,TOT_FT_PCT,TOT_FG3_PCT
3,2019,21900895,2020-03-01,1610612749,1610612766,1610612749,MIL,Milwaukee,AWAY,1628978,...,1.0,2.0,0.0,14.0,93.0,20.0,61.0,0.402,0.762,0.226
510,2019,21900882,2020-02-28,1610612749,1610612749,1610612760,MIL,Milwaukee,HOME,1628978,...,0.0,2.0,2.0,1.0,133.0,34.0,66.0,0.500,0.857,0.467
975,2019,21900858,2020-02-25,1610612749,1610612761,1610612749,MIL,Milwaukee,AWAY,1628978,...,0.0,0.0,2.0,2.0,108.0,23.0,53.0,0.381,0.833,0.333
1175,2019,21900851,2020-02-24,1610612749,1610612764,1610612749,MIL,Milwaukee,AWAY,1628978,...,0.0,3.0,2.0,-5.0,137.0,26.0,45.0,0.570,0.815,0.459
1634,2019,21900840,2020-02-22,1610612749,1610612749,1610612755,MIL,Milwaukee,HOME,1628978,...,0.0,1.0,1.0,8.0,119.0,35.0,57.0,0.527,0.692,0.341
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
574042,2012,21200004,2012-10-31,1610612761,1610612761,1610612754,TOR,Toronto,HOME,202334,...,2.0,2.0,1.0,1.0,88.0,18.0,42.0,0.363,0.842,0.353
574831,2012,11200089,2012-10-22,1610612761,1610612761,1610612749,TOR,Toronto,HOME,202334,...,0.0,0.0,0.0,NaN,104.0,24.0,49.0,0.455,0.714,0.450
575551,2012,11200060,2012-10-17,1610612761,1610612761,1610612764,TOR,Toronto,HOME,202334,...,1.0,2.0,3.0,NaN,104.0,23.0,40.0,0.500,0.741,0.267
576111,2012,11200030,2012-10-12,1610612761,1610612761,1610612765,TOR,Toronto,HOME,202334,...,1.0,2.0,2.0,NaN,82.0,17.0,41.0,0.394,0.955,0.294
576392,2012,11200023,2012-10-10,1610612761,1610612765,1610612761,TOR,Toronto,AWAY,202334,...,0.0,2.0,1.0,NaN,99.0,20.0,32.0,0.473,0.643,0.423

In [13]:
desc = Started_2019['PTS'].groupby([Started_2019['SEASON'], Started_2019['START_POSITION']]).describe()

In [14]:
final = pd.DataFrame(desc)

In [15]:
final.iloc[0,0]

94.0

In [16]:
SEASON = pd.DataFrame(final.droplevel('START_POSITION').index)
SP = pd.DataFrame(final.droplevel('SEASON').index)

In [17]:
final = final.reset_index(drop= True)
final_desc = pd.concat([SEASON, SP, final], axis=1, sort=False)
final_desc

,SEASON,START_POSITION,count,mean,std,min,25%,50%,75%,max
0,2003,F,94.0,20.085106,8.055799,2.0,14.00,20.0,26.0,41.0
1,2003,G,79.0,20.936709,8.179621,4.0,15.00,20.0,27.0,41.0
2,2004,C,3.0,5.666667,2.516611,3.0,4.50,6.0,7.0,8.0
3,2004,F,252.0,18.920635,9.258659,2.0,11.00,19.0,26.0,44.0
4,2004,G,9.0,24.444444,15.922556,6.0,14.00,23.0,31.0,56.0
5,2005,C,41.0,4.951220,3.331300,0.0,3.00,4.0,6.0,12.0
6,2005,F,283.0,23.226148,10.511987,0.0,16.00,23.0,31.0,52.0
7,2005,G,79.0,15.974684,6.374981,1.0,11.00,16.0,21.0,28.0
8,2006,C,172.0,13.505814,7.388546,0.0,8.00,13.0,18.0,35.0
9,2006,F,260.0,22.300000,10.046341,0.0,14.75,23.0,30.0,48.0
10,2006,G,135.0,14.444444,7.466009,0.0,8.50,15.0,19.5,35.0
11,2007,C,267.0,14.205993,7.272275,2.0,9.00,13.0,18.5,39.0
12,2007,F,509.0,19.518664,9.445354,0.0,12.00,19.0,26.0,51.0
13,2007,G,261.0,14.379310,8.580714,0.0,8.00,14.0,20.0,43.0
14,2008,C,420.0,13.564286,7.489255,0.0,8.00,13.0,18.0,45.0
15,2008,F,758.0,17.118734,9.514177,0.0,10.00,16.0,23.0,55.0
16,2008,G,586.0,15.081911,8.033271,0.0,9.00,14.0,21.0,43.0
17,2009,C,432.0,14.997685,7.177400,0.0,10.00,14.0,20.0,37.0
18,2009,F,854.0,16.778689,9.280390,0.0,10.00,15.0,22.0,50.0
19,2009,G,958.0,14.677453,7.400566,0.0,9.00,14.0,19.0,42.0
20,2010,C,640.0,13.393750,8.072905,0.0,7.00,12.0,18.0,46.0
21,2010,F,1092.0,17.076923,8.916022,0.0,11.00,16.0,23.0,51.0
22,2010,G,1101.0,16.454133,8.239535,0.0,10.00,16.0,22.0,44.0
23,2011,C,438.0,11.860731,7.623357,0.0,7.00,11.0,16.0,51.0
24,2011,F,921.0,16.400651,9.159288,0.0,9.00,16.0,22.0,45.0
25,2011,G,1246.0,14.999197,7.610023,0.0,10.00,15.0,20.0,45.0
26,2012,C,806.0,12.709677,7.059469,0.0,7.00,12.0,18.0,39.0
27,2012,F,1836.0,14.862745,8.303881,0.0,9.00,14.0,20.0,50.0
28,2012,G,1857.0,15.782445,8.041987,0.0,10.00,15.0,21.0,54.0
29,2013,C,849.0,12.667845,6.656704,0.0,8.00,12.0,17.0,37.0
30,2013,F,1955.0,16.595908,8.875310,0.0,10.00,16.0,22.0,62.0
31,2013,G,2339.0,16.374091,8.132449,0.0,10.50,16.0,21.0,47.0
32,2014,C,1311.0,12.681922,6.432525,0.0,8.00,12.0,17.0,37.0
33,2014,F,2555.0,14.701761,7.997913,0.0,9.00,14.0,20.0,47.0
34,2014,G,3230.0,15.430341,8.365820,0.0,10.00,15.0,20.0,57.0
35,2015,C,1705.0,12.219941,6.723606,0.0,7.00,11.0,16.0,43.0
36,2015,F,3642.0,14.019769,7.710581,0.0,8.00,13.0,19.0,59.0
37,2015,G,3735.0,16.054886,8.734244,0.0,10.00,15.0,21.0,53.0
38,2016,C,2046.0,13.340665,7.305140,0.0,8.00,12.0,18.0,47.0
39,2016,F,4078.0,14.484306,8.373230,0.0,8.00,13.0,20.0,50.0
40,2016,G,4086.0,16.573177,9.418147,0.0,9.00,16.0,22.0,70.0
41,2017,C,2100.0,13.469524,7.420118,0.0,8.00,13.0,18.0,56.0
42,2017,F,4492.0,13.944791,8.136832,0.0,8.00,13.0,19.0,57.0
43,2017,G,4431.0,16.085759,8.765459,0.0,10.00,15.0,21.0,60.0
44,2018,C,2468.0,14.184765,7.643605,0.0,8.00,13.0,19.0,43.0
45,2018,F,4969.0,13.981284,8.347154,0.0,8.00,13.0,19.0,56.0
46,2018,G,5039.0,16.004564,9.145866,0.0,9.00,15.0,21.0,61.0
47,2019,C,1930.0,12.009326,7.418394,0.0,6.00,11.0,16.0,49.0
48,2019,F,3860.0,14.348964,8.536144,0.0,8.00,13.0,20.0,51.0
49,2019,G,3860.0,16.089896,9.521621,0.0,9.00,15.0,22.0,61.0

In [18]:
Season2019 = Started_2019[Started_2019['SEASON'] == 2019]
Season2018 = Started_2019[Started_2019['SEASON'] == 2018]
Last2Season = Season2019.append(Season2018)
Last2Season.drop_duplicates(inplace = True)

In [22]:
desc2 = Last2Season['PTS'].groupby([Last2Season['PLAYER_ID'], Last2Season['START_POSITION']]).describe()
descplayer = pd.DataFrame(desc2)
ID = pd.DataFrame(descplayer.droplevel('START_POSITION').index)
POS = pd.DataFrame(descplayer.droplevel('PLAYER_ID').index)
descplayer = descplayer.reset_index(drop= True)
final_descplayer = pd.concat([ID, POS ,descplayer], axis=1, sort=False)
final_descplayer.sort_values(by=['mean'],inplace=True,ascending=False)
final_descplayer

,PLAYER_ID,START_POSITION,count,mean,std,min,25%,50%,75%,max
189,203507,G,1.0,43.000000,NaN,43.0,43.00,43.0,43.00,43.0
56,201935,G,154.0,34.928571,10.395516,12.0,28.25,35.0,41.00,61.0
498,1629035,G,1.0,30.000000,NaN,30.0,30.00,30.0,30.00,30.0
107,202695,G,3.0,29.666667,1.527525,28.0,29.00,30.0,30.50,31.0
58,201939,G,103.0,26.912621,9.356875,5.0,20.50,26.0,33.50,51.0
...,...,...,...,...,...,...,...,...,...,...
200,203648,C,1.0,4.000000,NaN,4.0,4.00,4.0,4.00,4.0
408,1628403,C,1.0,4.000000,NaN,4.0,4.00,4.0,4.00,4.0
299,1626245,C,2.0,3.500000,3.535534,1.0,2.25,3.5,4.75,6.0
0,2199,C,11.0,3.000000,2.408319,0.0,1.50,2.0,4.00,8.0
501,1629057,C,5.0,2.000000,1.414214,0.0,2.00,2.0,2.00,4.0

In [25]:
unique_players = players.drop(columns=['TEAM_ID', 'SEASON'])
unique_players.drop_duplicates(inplace = True)
final_descplayer_name = pd.merge(final_descplayer, unique_players, on='PLAYER_ID')
final_descplayer_name = final_descplayer_name[['PLAYER_ID','START_POSITION','PLAYER_NAME','count','mean','std','min','25%','50%','75%','max']]
final_descplayer_name.sort_values(by=['START_POSITION','mean'],inplace=True,ascending=False)

,PLAYER_ID,START_POSITION,PLAYER_NAME,count,mean,std,min,25%,50%,75%,max
0,203507,G,Giannis Antetokounmpo,1.0,43.000000,NaN,43.0,43.00,43.0,43.00,43.0
2,201935,G,James Harden,154.0,34.928571,10.395516,12.0,28.25,35.0,41.00,61.0
3,1629035,G,Carsen Edwards,1.0,30.000000,NaN,30.0,30.00,30.0,30.00,30.0
4,202695,G,Kawhi Leonard,3.0,29.666667,1.527525,28.0,29.00,30.0,30.50,31.0
6,201939,G,Stephen Curry,103.0,26.912621,9.356875,5.0,20.50,26.0,33.50,51.0
...,...,...,...,...,...,...,...,...,...,...,...
549,203648,C,Thanasis Antetokounmpo,1.0,4.000000,NaN,4.0,4.00,4.0,4.00,4.0
550,1628403,C,Caleb Swanigan,1.0,4.000000,NaN,4.0,4.00,4.0,4.00,4.0
551,1626245,C,Cristiano Felicio,2.0,3.500000,3.535534,1.0,2.25,3.5,4.75,6.0
552,2199,C,Tyson Chandler,11.0,3.000000,2.408319,0.0,1.50,2.0,4.00,8.0
553,1629057,C,Robert Williams III,5.0,2.000000,1.414214,0.0,2.00,2.0,2.00,4.0

In [30]:
final_descplayer_name[final_descplayer_name['START_POSITION'] == 'G'].head(15)

,PLAYER_ID,START_POSITION,PLAYER_NAME,count,mean,std,min,25%,50%,75%,max
0,203507,G,Giannis Antetokounmpo,1.0,43.000000,NaN,43.0,43.00,43.0,43.0,43.0
2,201935,G,James Harden,154.0,34.928571,10.395516,12.0,28.25,35.0,41.0,61.0
3,1629035,G,Carsen Edwards,1.0,30.000000,NaN,30.0,30.00,30.0,30.0,30.0
4,202695,G,Kawhi Leonard,3.0,29.666667,1.527525,28.0,29.00,30.0,30.5,31.0
6,201939,G,Stephen Curry,103.0,26.912621,9.356875,5.0,20.50,26.0,33.5,51.0
7,203081,G,Damian Lillard,157.0,26.681529,9.909228,5.0,20.00,26.0,33.0,61.0
8,203078,G,Bradley Beal,133.0,26.398496,8.974661,5.0,20.00,26.0,31.0,55.0
10,1626164,G,Devin Booker,125.0,26.000000,9.584934,6.0,20.00,26.0,32.0,59.0
11,1629029,G,Luka Doncic,101.0,25.158416,7.871128,2.0,20.00,25.0,31.0,42.0
13,201566,G,Russell Westbrook,131.0,24.473282,8.424623,7.0,18.50,23.0,30.0,45.0
14,203897,G,Zach LaVine,130.0,24.300000,8.790102,5.0,19.00,24.0,29.0,49.0
16,1629632,G,Coby White,1.0,24.000000,NaN,24.0,24.00,24.0,24.0,24.0
17,202681,G,Kyrie Irving,100.0,23.840000,9.641786,0.0,17.00,23.0,30.0,54.0
18,1628378,G,Donovan Mitchell,147.0,23.748299,8.429273,3.0,19.00,24.0,29.5,46.0
19,202689,G,Kemba Walker,135.0,23.703704,10.126863,0.0,16.50,23.0,30.0,60.0

In [31]:
final_descplayer_name[final_descplayer_name['START_POSITION'] == 'C'].head(15)

,PLAYER_ID,START_POSITION,PLAYER_NAME,count,mean,std,min,25%,50%,75%,max
507,203954,C,Joel Embiid,124.0,25.096774,8.771183,0.0,19.75,24.0,32.00,49.0
508,1626157,C,Karl-Anthony Towns,121.0,24.603306,7.856504,8.0,19.00,25.0,30.00,42.0
350,204001,C,Kristaps Porzingis,17.0,23.117647,9.505803,9.0,15.00,24.0,28.00,38.0
323,203944,C,Julius Randle,33.0,22.666667,6.273290,6.0,19.00,22.0,26.00,37.0
301,1627863,C,Danuel House Jr.,1.0,21.000000,NaN,21.0,21.00,21.0,21.00,21.0
327,200746,C,LaMarcus Aldridge,56.0,20.392857,7.664982,6.0,15.75,20.0,25.25,38.0
317,203076,C,Anthony Davis,18.0,20.333333,10.278476,6.0,13.25,17.0,28.50,41.0
319,203999,C,Nikola Jokic,148.0,20.074324,8.240510,2.0,15.00,20.0,24.00,47.0
325,1628381,C,John Collins,11.0,19.818182,6.779649,8.0,16.50,18.0,23.00,33.0
509,202696,C,Nikola Vucevic,142.0,19.471831,6.307368,3.0,15.00,20.0,24.00,36.0
510,1628392,C,Isaiah Hartenstein,2.0,18.000000,1.414214,17.0,17.50,18.0,18.50,19.0
341,1627734,C,Domantas Sabonis,15.0,17.933333,3.634491,13.0,15.50,18.0,19.50,27.0
354,1629028,C,Deandre Ayton,98.0,17.285714,6.209404,2.0,14.00,17.5,20.75,33.0
511,203083,C,Andre Drummond,146.0,17.267123,6.169213,0.0,13.00,16.5,21.00,32.0
512,1626149,C,Montrezl Harrell,8.0,17.000000,7.745967,10.0,11.00,16.5,18.25,34.0